### PR TITLE
Upgrade to Rails 5

### PR DESCRIPTION
**Pull request by jfhamlin**
Rails 5 includes rails-api, so we don't have to pull it in separately, and the latest `ActiveRecord` adds some useful helpers (see `left_outer_joins` below).

### CODE REVIEW

**Comment by lelandg559** [comment]
some rspec tests are failing still, investigating

**Comment by lelandg559** [comment]
Verified locally

**Comment by jjfreund** [comment]
After the upgrade, I am prompted to enter the following command:

bin/rails db:environment:set RAILS_ENV=development

setting this variable allowed me to proceed.

**Comment by jjfreund** [comment]
Confirmed that the app is operational post-upgrade in rails 5.

**Pull request merged**
