### PR TITLE
fix(geocoding): remove error catching for google api key problems for…

### PR DESCRIPTION
**Pull request by lgarofalo**
… geocoding

### CODE REVIEW

**Comment by richardxia** [comment]
It looks like you might need to set the right environment variables for the Postman tests to pass on Travis.

**Comment by Maxastuart** [comment]
Is this related to https://github.com/ShelterTechSF/askdarcel-web/issues/410 ?

**Comment by richardxia** [comment]
Is this still relevant, or should we close it out? (Just going through really old PRs right now.)

**Comment by lgarofalo** [comment]
Going to time this out, doesn't seem needed.

**Pull request closed without merging**
