### PR TITLE
chore(data): add eligibilities

### PR DESCRIPTION
**Pull request by lgarofalo**
Requested, will be manually run.

### CODE REVIEW

**Review by schroerbrian — APPROVED** [review]
Looks great! Sorry i missed that this was up earlier

**Comment by lgarofalo** [comment]
I need to separately fix test build, but I will run this now.

**Comment by lgarofalo** [comment]
```
askdarcel=> select * from eligibilities where created_at > now() - interval '5 minutes';
 id |             name              |         created_at         |         updated_at         | feature_rank | is_parent 
----+-------------------------------+----------------------------+----------------------------+--------------+-----------
 32 | Toddler Age                   | 2024-05-07 16:41:43.838673 | 2024-05-07 16:41:43.838673 |              | f
 33 | Preteen                       | 2024-05-07 16:41:43.838673 | 2024-05-07 16:41:43.838673 |              | f
 34 | Transitional Aged Youth (TAY) | 2024-05-07 16:41:43.838673 | 2024-05-07 16:41:43.838673 |              | f
 35 | Preschool Student             | 2024-05-07 16:41:43.838673 | 2024-05-07 16:41:43.838673 |              | f
 36 | Elementary School Student     | 2024-05-07 16:41:43.838673 | 2024-05-07 16:41:43.838673 |              | f
 37 | Postgraduate Student          | 2024-05-07 16:41:43.838673 | 2024-05-07 16:41:43.838673 |              | f
 38 | Married without children      | 2024-05-07 16:41:43.838673 | 2024-05-07 16:41:43.838673 |              | f
(7 rows)
```

**Comment by richardxia** [comment]
Merging, since this was already run in prod.

**Pull request merged**
